config/routes.rb
Rails.application.routes.draw do
  #devise_for :users, controllers: { registrations: "users/registrations" }
  root to: "pages#home"

  get '/auth/:provider/callback' => 'user_sessions#create'
  get '/auth/failure' => 'user_sessions#failure'

  # Custom logout
  match '/logout', :to => 'user_sessions#destroy', via: :all
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authorization

  protect_from_forgery with: :exception

  responders :flash
  respond_to :html

  def login_required
    if !current_user
      respond_to do |format|
        format.html  {
          redirect_to '/auth/sso'
        }
        format.json {
          render json: { 'error' => 'Access Denied' }.to_json
        }
      end
    end
  end

  def current_user
    return nil unless session[:user_id]
    @current_user ||= User.find_by(uid: session[:user_id]['uid'])
  end
  helper_method :current_user
end

app/controllers/concerns/authorization.rb
module Authorization
  extend ActiveSupport::Concern

  included do
    include Pundit
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  end

  private

  def user_not_authorized
    redirect_to(root_path)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :login_required

  def home
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :login_required, only: [ :destroy ]

  # omniauth callback method
  #
  # First the callback operation is done
  # inside OmniAuth and then this route is called
  def create
    omniauth = env['omniauth.auth']
    logger.debug "+++ #{omniauth}"

    user = User.find_by(uid: omniauth['uid'])
    if not user
      # New user registration
      user = User.new(uid: omniauth['uid'])
    end
    user.email = omniauth['info']['email']
    user.save

    #p omniauth

    # Currently storing all the info
    session[:user_id] = omniauth

    flash[:notice] = "Successfully logged in"
    redirect_to root_path
  end

  # Omniauth failure callback
  def failure
    flash[:notice] = params[:message]
  end

  # logout - Clear our rack session BUT essentially redirect to the provider
  # to clean up the Devise session from there too !
  def destroy
    session[:user_id] = nil

    flash[:notice] = 'You have successfully signed out!'
    redirect_to "#{ENV["CUSTOM_PROVIDER_URL"]}/users/sign_out"
  end
end

app/views/application/_footer.html.slim
footer.row
  .columns
    p &copy; Flatstack #{Time.zone.today.year}

app/views/application/_messages.html.slim
- flash.each do |type, content|
  div(class="callout #{type}" data-closable)
    = content
    button.close-button(tabindex="0" aria-label="Dismiss alert" type="button" data-close)
      span aria-hidden="true" &times;

app/views/application/_navigation.html.slim
.title-bar data-hide-for="medium" data-responsive-toggle="navigation_menu"
  button.menu-icon data-toggle="" type="button"
  title-bar-title Menu

nav.top-bar#navigation_menu
  = render "navigation_main"
  = render "navigation_user"

app/views/application/_navigation_main.html.slim
.top-bar-left
  ul.menu
    li = link_to "Rails Base example site", root_path
    - if current_user
      = active_link_to "Home", root_path, active: :exclusive, wrap_tag: :li

app/views/application/_navigation_user.html.slim
ul.top-bar-right.menu.dropdown(data-dropdown-menu)
  - if current_user
    li
      a = current_user.full_name
      ul.menu
        li = link_to "Sign out", logout_path

app/views/layouts/application.html.slim
doctype html

html class="no-js" lang="en"

  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    meta name="robots" content="NOODP,NOYDIR"

    = metamagic site: "RailsBase", title: %i(title site), separator: " - "
    = csrf_meta_tags

    = stylesheet_link_tag :application

    = javascript_tag "window.App = {}"

    == analytics_init if GA.tracker

  body
    = render "navigation"
    = render "messages"

    main.container
      = yield

    = render "footer"

    javascript:
      App.currentUserData = #{{current_user.to_json}};

    = javascript_include_tag :application

app/views/pages/home.html.slim
.row
  .columns
    h2
      = title("Home")

app/views/users/shared/_links.html.slim
h6 Anything else?
ul.no-bullet
  - if controller_name != "sessions"
    li = link_to "Sign in", new_session_path(resource_name)

  - if devise_mapping.registerable? && controller_name != "registrations"
    li = link_to "Create a new account", new_registration_path(resource_name)

  - if devise_mapping.recoverable? && controller_name != "passwords"
    li = link_to "Forgot your password?", new_password_path(resource_name)

  - if devise_mapping.confirmable? && controller_name != "confirmations"
    li = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)

  - if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != "unlocks"
    li = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)

  - if devise_mapping.omniauthable?
    - resource_class.omniauth_providers.each do |provider|
      li = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)